### ISSUE TITLE
Version 2.1.0 Tasks

### ISSUE THREAD

**Issue by Prophet731** [AdKats/BFAdminCP#180] opened 2016-03-31 08:52 UTC
- [x] Fix incorrect use of the report system commands.

**Comment by iraqiboy90** [comment] 2016-03-31 18:50
It seems like xcache infact do have a variable cache (object caching), if i'm not wrong.
But, I see that Laravel 5 does not support xcache by default.
Can you add support for that?
https://laravel.com/docs/5.2/cache#adding-custom-cache-drivers

**Comment by iraqiboy90** [comment] 2016-03-31 19:02
Issue:
- When acting on report at the panel and selecting "Player Report (ignore)", it will mark the report as "Accept Round Report" on Record History and then add another record of "Report Player (Ignored)".

Will confuse admins cause of contradicting records...

**Comment by ColColonCleaner** [comment] 2016-03-31 22:09
That is not at all correct.

Accept round report, the !accept command in game, is used to confirm reports without acting on them. When the !accept command is issued the report associated with it gets its action marked as Report Player (confirmed).

The report gets its action changed to:
player_report_ignore
player_report_deny
player_report_confirm

The record showing the admin did the accept/ignore/deny gets its command and action:
admin_accept
admin_ignore
admin_deny

Understand? The admin_deny command causes a report to be changed to player_report_deny.

Do not send records to AdKats with Y, for admin_accept/deny/ignore, there is no parser for those because report IDs expire at round end and having access to call those commands via DB later wouldn't be good.

**Comment by Prophet731** [comment] 2016-04-01 06:28
> It seems like xcache infact do have a variable cache (object caching), if i'm not wrong.
> But, I see that Laravel 5 does not support xcache by default.
> Can you add support for that?
> https://laravel.com/docs/5.2/cache#adding-custom-cache-drivers

See this and tell me if it works or not.

http://laravel-recipes.com/recipes/100/setting-up-the-xcache-cache-driver

**Comment by Prophet731** [comment] 2016-04-21 08:13
I've fixed the incorrect report id. I only updated it in one place the first time and forgot about the second place. It should be working as intended now. @iraqiboy90 can you do a git pull (if your have it setup that way) and tell me if those errors no longer show for a report.

**Closed** 2017-10-15 19:19 UTC
